### ISSUE TITLE
Failed to login using the link in the email.

### ISSUE THREAD

**Issue by piratov** [tinode/webapp#100]
If you want to ask a question, please post to https://groups.google.com/d/forum/tinode instead.
https://groups.google.com/g/tinode/c/xYcemyHlQbI

**Describe the bug**
I tested sending authorization mail, there were questions. How to repeat sending mail with authorization code again?
I also noticed from the letter via a direct link (http://server/#cred?method=email&code=695957&token=B-J1WhBHJjfPOwZjAAABAAIA3yd6bXqDFgvw3H44Fsq0v9Yp4qqIzj1a6ADpiQVFPgU=) it was not possible to log in. It turned out only when I repeated the values 695957 in the field with my hands.

**Comment by piratov** [comment]
Confirmation of mail by the link from the letter passes positively.

However, it is not automatically authorized by login.
If you manually enter the confirmation code, authorization with entry is automatic.

**Comment by or-else** [comment]
I believe this is fixed now. The requires server update from the latest [devel branch](https://github.com/tinode/chat/tree/devel).

**Comment by piratov** [comment]
> I believe this is fixed now. The fix requires server update from the latest [devel branch](https://github.com/tinode/chat/tree/devel).

Wonderful, thank you
