### ISSUE TITLE
little suggestions messages-panel, contact-box for css

### ISSUE THREAD

**Issue by piratov** [tinode/webapp#102]
1 Align repost
<img src="https://user-images.githubusercontent.com/17856390/203527274-49a961f5-0f91-4a19-ad0d-accab67e4530.png" width="320">

https://github.com/tinode/webapp/blob/devel/css/base.css
line 1942....

```
.bubble div.message-content {
  position: relative;
  margin: 0;
  width: 100%;
  max-width: 36rem;
  overflow-wrap: anywhere;
  word-break: break-word;
  padding: 0 0.75rem 0 0.75rem;
}
```

align  <img src="https://user-images.githubusercontent.com/17856390/203528104-3c5c89c0-eacb-445a-8343-136667519563.png" width="320">

2 Add cursor: pointer;
https://github.com/tinode/webapp/blob/devel/css/base.css
line 942....

```
.contact-box > li {
  position: relative;
  display: flex;
  padding: 0.35rem 0.25rem 0.5rem 0.35rem;
  min-height: 3.75rem;
  flex-grow: 0;
  flex-shrink: 0;
  /* partial bottom border */
  background: linear-gradient(to right, transparent 3.5rem, #eee 1px, #eee 100%) 0 100% / 100% 1px no-repeat, #fff;
  overflow-x: hidden;
  cursor: pointer;
}
```
![image](https://user-images.githubusercontent.com/17856390/203530817-56008f1c-870b-4312-8a06-1d03f36bb749.png)

**Comment by or-else** [comment]
Part 1 fixed in https://github.com/tinode/webapp/commit/6de41f49881464d3d009ad55239e7e890ba4870c.

**Comment by or-else** [comment]
2 fixed in https://github.com/tinode/webapp/commit/1913ed0c118e74c3003020e4ee42b36ad87fb65f

**Comment by piratov** [comment]
Thanks
