### ISSUE TITLE
Mobile web app should not focus input field to avoid opened keyboard

### ISSUE THREAD

**Issue by pwFoo** [tinode/webapp#111]
If I view a chat in smartphone portrait format the input field is focused and so the keyboard opened.
The problem have of screen is lost to see messages / images and can't directly access menu (e.g. to start a call). Top line isn't fixed on top and so scrolled out.

![image](https://user-images.githubusercontent.com/333408/212859933-426350a6-f33a-46e9-8af7-a34ca52f74ce.png)

**Comment by or-else** [comment]
Added in https://github.com/tinode/webapp/commit/424a8b64bf973536fbc1ef2cf595557bbfd391f7. Please verify.

**Comment by or-else** [comment]
This is released.
