### ISSUE TITLE
Web app ignore newer version

### ISSUE THREAD

**Issue by pwFoo** [tinode/webapp#114]
Hi,
I updated my "old" tinode server from 0.18 to 0.20 and now 0.21.0-rc1, but can't force the web app to update to the latest version. Restartet, reloaded in browser and also deleted all website data / settings, but still old client version is shown?

Got it updated on desktop Chrome browser. Fail with Chrome for Android @ OnePlus

![image](https://user-images.githubusercontent.com/333408/212879678-ac35d086-8064-4988-8adf-67fff2f9be57.png)

Feature request: Add a force update button somewhere to update the client side (cached) app data?

**Comment by or-else** [comment]
I cannot reproduce

<img width="336" alt="Screenshot 2023-01-17 at 08 36 58" src="https://user-images.githubusercontent.com/5938143/212958046-ea0c65df-ba19-4c33-afe8-040f55e173f9.png">

**Comment by pwFoo** [comment]
I have 3 web app clients.
Smartphones stick to 0.18.x and 0.20.2 without a way to force refresh the web app. Delete browser cache and website settings isn't helping here. Both are Chrome for Android with installed to homescreen. 
Desktop Chrome works fine and is up to date connected to the same server. Just not installed to homescreen / webapp.

Maybe my problem is related to the updates from 0.18.x to 0.21.0-rc1 via 0.20.2. A one time "fix" to force a update / refresh would be nice.

**Comment by or-else** [comment]
https://browserhow.com/how-to-do-hard-refresh-and-reload-webpage-in-chrome-android/
