### ISSUE TITLE
Modify Appearance

### ISSUE THREAD

**Issue by theslash** [tinode/webapp#115]
So,
I may be on the wrong track here.
I have a Tinode Server running in docker. 

And cloned this repostiory to a webserver. 
The UI is opening, I can login and use everything.
But I need to modify the UI, change the logo, a few colors and so on.

I tried to modify the /src/views/logo-view.jsx but it has no effect.

I understand that I somehow need to build the project but cant find a how-to. 
And otherwise, I understand this is not a standalone app, so how would I go when I ran the server directly?

thanks in advance

**Comment by or-else** [comment]
Please follow installation instructions to run Tinode:
https://github.com/tinode/chat/blob/master/INSTALL.md

If you want to build TinodeWeb then the command you are looking for is [npm run build](https://www.google.com/search?q=npm+run+build).

Please direct further questions to the forum.
