### ISSUE TITLE
Browser notifications

### ISSUE THREAD

**Issue by pwFoo** [tinode/webapp#12]
"Browser push notifications are not implemented."

Is it planned in the near future? Would be great for desktop browser and closed browser notifications with mobile / android.

**Comment by or-else** [comment]
I would say it's a couple of months away.

**Comment by pwFoo** [comment]
@or-else 
Thanks for your quick reply!
Do you plan to implement a fix solution like FCM or by browser / device decision (Chrome, Firefox, Edge)?

Push notifications would be awesome :)

**Comment by pwFoo** [comment]
I'm new with git pull requests and programming (golang, web notifications api, ...). So I don't know if I really can help here, but I'll take a look. 

Tried a little bit with php / javascript based on [that example](https://webpushdemo.azurewebsites.net/) which uses browser / vendor dependent push service. 

> e.g. Firebase Cloud Messaging (FCM), Mozilla Cloud Services (MCS), and Windows Push Notification Service (WNS) depending on which browser is being used

I would prefer to let the device choose the push service itself (Edge -> WNS, Chrome / Android -> FCM, FIrefox -> MCS).

**Comment by or-else** [comment]
FCM supports all browsers with support for [Web Notifications API](https://developer.mozilla.org/en-US/docs/Web/API/notification). Which means everything but Safari is supported
https://firebase.googleblog.com/2018/05/web-notifications-api-support-now.html

Which means everything but Safari is supported:
https://caniuse.com/#feat=push-api

**Comment by pwFoo** [comment]
Ok, but FCM is related to google, right? So maybe some users use Edge / Firefox / Opera instead of Chrome to  avoid Google? Chrome and Android is related to Google / Gmail and FCM would be fine. 
Client side could be done with Javascript (un-/subscribe) and send subscription to the Server.  
Server use the client subscription with preferred service.
How complexe is server side? Pub / priv key and call the subacriber service for example with curl? Service url is given by client service subscription.

**Comment by or-else** [comment]
It's a matter of practicality. FCM is done. Non-FCM pushes are not done. I personally have no time for it. If someone wants to implement them - great, I'll support the effort.

**Comment by or-else** [comment]
Any update on this?

**Comment by pwFoo** [comment]
I built cross browser notifications based on the demo. Reduzed to the needed code. But it needs some rewrite / code clean up first.

And I don't know how to implement to the react client.
Any plans to separate html / templates and js to different files? Should be easier to read, modify or maintain.

**Comment by or-else** [comment]
> I built cross browser notifications based on the demo

Great. 

> Any plans to separate html / templates and js to different files?

React components are expected to include html (jsx) and js in the same file.

**Comment by pwFoo** [comment]
Maybe I take a look into the tinode.js lib how to build a custom client, but at the moment I have no time to play with or rewrite the notification code. I think I need some weeks to do other tasks first...

**Comment by or-else** [comment]
> After some rewrite I could send you the client side notification code to take a look?

Absolutely. Would be glad to see it. 

I'll close this issue. Once you get to working on it, please open a new one or write to https://groups.google.com/d/forum/tinode

**Comment by pwFoo** [comment]
@or-else 
https://groups.google.com/forum/#!topic/tinode/k8LzEApbwTM
With link to a demo / repo

**Comment by pwFoo** [comment]
@or-else 
Do I need a FCM account for push notifications?

**Comment by or-else** [comment]
Yes, you need an FCM account.

**Comment by pwFoo** [comment]
With webpush-go library there is no account needed, but at the moment I haven't time to rewrite / cleanup the client side javascript code...

Do you know an easy howto? I need to create a FCM account to add push to my tinode test system.

**Comment by or-else** [comment]
Go to https://console.firebase.google.com/
Create an account, create your project, configure it, start pushing. The FCM push is free.

**Comment by pwFoo** [comment]
Account and project created. 
projekt id added to docker run, but `FCM_CRED_FILE`?

**Comment by or-else** [comment]
https://console.firebase.google.com/project/YOUR-PROJECT-NAME-HERE/settings/serviceaccounts/adminsdk

**Comment by or-else** [comment]
And you need to enable messaging api at console.cloud.google.com

**Comment by pwFoo** [comment]
Ok. Activated messaging and found a snippet (node.js, java, python, go) on "Firebase Admin SDK" page, but no json file / path / url / content.

It looks like I have to add a file to the container web path?

**Comment by or-else** [comment]
<img width="1089" alt="screen shot 2018-09-22 at 16 37 31" src="https://user-images.githubusercontent.com/5938143/45917829-232f5600-be86-11e8-9e95-147f8591a70e.png">

Keep in mind that it exists, it works. Yes, it is complex. Yes, it is convoluted. But with enough persistence it works.

**Comment by pwFoo** [comment]
Strange...

Verified file and content is correct mapped inside container. And also checked generated tinode config...
cred file isn't read as should?

tinode container runs as root, 
file in volume exists
content is the downloaded json file

But tinode container stops with (got the logs with a /var/log/ volume to have persistent logs without running container...)

```
2018/09/22 15:01:23 Server v0.15:/opt/tinode/tinode:v0.15.6-rc5; db: 'mysql'; pid 46; 2 process(es)
2018/09/22 15:01:23 Using config from '/opt/tinode/working.config'
2018/09/22 15:01:23 Running as a standalone server.
2018/09/22 15:01:23 Failed to initialize push notifications:missing credentials
```

browser dependent push service just work with a priv / pub key generated server side. No account needed. So if tinode switches in the future it would be easier to use push notifications.

**Comment by pwFoo** [comment]
Each time I get 
````
2018/09/22 15:15:23 Failed to initialize push notifications:missing credentials
```

But don't know how to debug it.

**Comment by pwFoo** [comment]
It's a locale problem because there is no traffic to FCM outgoing. So why the creds not found if path / file in config is fine and the cred file exists?

**Comment by or-else** [comment]
It's my bug. The docker template has `credential_file` while the code expects `credentials_file`.

**Comment by or-else** [comment]
I'll release a new docker with the fix tomorrow.

**Comment by or-else** [comment]
0.15.6 released.

**Comment by pwFoo** [comment]
Looks like there is still a problem? I'm able to start the tinode app after I changed to the latest image.
Tested with Chrome, Chrome Incognito and a mobile. No push notifications. 
```
2018/09/23 15:57:30 fcm push failed http error status: 403; reason: sender id does not match regisration token; code: mismatched-credential; details: The caller does not have permission
```

**Comment by or-else** [comment]
Yep. I forgot about hardcoded key and sender ID in the javascript files too:
https://github.com/tinode/webapp/blob/master/src/webapp.jsx#L38
https://github.com/tinode/webapp/blob/master/service-worker.js#L7

No I need to figure out how to pass then to the webapp in the container.

**Comment by or-else** [comment]
But the error you are getting means that the server is set up correctly.

**Comment by pwFoo** [comment]
Yes, it looks good, just the right credentials are missing.

**Comment by or-else** [comment]
0.15.7-rc1 takes two new credentials for the client-side.

**Comment by pwFoo** [comment]
My I have still problems after update.

![image](https://user-images.githubusercontent.com/333408/46032032-dc966180-c0fa-11e8-8bb0-7a8bdfde110c.png)

I can't de-/activate the Notification alert checkbox by click / keyboard.

![image](https://user-images.githubusercontent.com/333408/46032112-051e5b80-c0fb-11e8-9205-5561606740b3.png)

Same with mobile (can't check the checkbox). Desktop and mobile same problem after clear cache / temp data / cookie / ... and incognito browser too.

Developer tools console:
````
Failed to initialize push notifications {code: "messaging/bad-sender-id", message: "Messaging: Please ensure that 'messagingSenderId' …ebase.initializeApp(). (messaging/bad-sender-id).", stack: "FirebaseError: Messaging: Please ensure that 'mess…s://chat.it-dengler.de/umd/index.prod.js:1:70982)"}
```

**Comment by or-else** [comment]
Are you using correct sender ID? 

If you connect to a running container
```
docker exec -it name-of-the-running-container /bin/bash
```
what's the content of /firebase-init.js?
```
cat /firebase-init.js
```

**Comment by or-else** [comment]
The content of /firebase-init.js is public, you can freely post it here.

**Comment by or-else** [comment]
Or, actually, see the contents of firebase-init.js in the browser: 
http://localhost:6060/firebase-init.js

**Comment by pwFoo** [comment]
File doesn't exist
```
/opt/tinode # cat /firebase-init.js
cat: can't open '/firebase-init.js': No such file or directory
```

**Comment by pwFoo** [comment]
Web file exists, but empty...
```
const FIREBASE_INIT={messagingSenderId: "", messagingVapidKey: ""};
```

I think something is wrong with my docker command... Let me check...

**Comment by or-else** [comment]
did you provide the values on the command line when launching the container?
`--env FCM_SENDER_ID=... --env FCM_VAPID_KEY=...`

**Comment by or-else** [comment]
it's actually `cat /static/firebase-init.js`

**Comment by pwFoo** [comment]
Problem are the missing env variables...
But where I get sender_id (fcm project_id?) and vapid key?

**Comment by pwFoo** [comment]
FCM is... annoying
```
2018/09/25 18:30:23 fcm push failed http error status: 403; reason: sender id does not match regisration token; code: mismatched-credential; details: The caller does not have permission

```

**Comment by or-else** [comment]
This error means your client-side credentials do not match your server-side credentials.

**Comment by or-else** [comment]
You can try sending a push from the firebase console to the client side token. This way you can be sure that the client side is set up correctly.

**Comment by pwFoo** [comment]
Where can I send a test push?

It would be so easy with browser dependent push instead of FCM. I hope it'll switch in the (near) future. 
I think I'll test it tomorrow if I have some time... 
Frustrating to set it up :(

**Comment by or-else** [comment]
> Where can I send a test push?

Go to console.firebase.google.com, scroll left-side menu to the bottom and click on Cloud Messaging:
https://console.firebase.google.com/u/0/project/YOUR-PROJECT-NAME/notification

**Comment by pwFoo** [comment]
I updated to latest 0.15.7-rc2 image and (offline) notifications work fine without change anything with the FCM configuration! :)

- With opend / active app the user just get the notification count and sound of tinode app.
- If the app is opened but in background you get tinode sound first and then system (android) notification. That's ok to not miss the message if the display is off
- app closed I just get the system notification
👍 

But you should tweak the notification 
- chat / contact in notification title?
- click the notification should open / redirect to the app! That's missing at the moment.

notification click event could be something like following code?
```
self.addEventListener('notificationclick', function(event) {
    event.notification.close();

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true })
            .then(function(clientList) {
                if (clientList.length > 0) {
                    let client = clientList[0];

                    for (let i = 0; i < clientList.length; i++) {
                        if (clientList[i].focused) {
                            client = clientList[i];
                        }
                    }
                    console.log("FOCUS CLIENT: ", client);
                    return client.focus();
                }
                console.log(clients);
                return clients.openWindow(event.notification.data);
            })
    );
});
```

**Comment by or-else** [comment]
Thanks for the suggestion. I'll look into it once I finish the current work on password reset.

**Comment by pwFoo** [comment]
Push works at the moment with latest image. 

But I'll notified about own messages with "app updated in background" (translated) notifications.

**Comment by pwFoo** [comment]
One more improvement:
Group notifications to keep status  bar clean.
At the moment each message have it's own notification icon

**Comment by pwFoo** [comment]
Group all app notifications to one or maybe by chat?

**Comment by or-else** [comment]
The code in `devel` branch now has
* Grouping notifications by topic
* Clicking on a notification takes you to the topic.

**Comment by pwFoo** [comment]
I'll update my tinode (docker container) to test it. Maybe could take some days because lack of time... Thanks!

**Comment by pwFoo** [comment]
Updated tinode server. I'll do some more tests next week. If any problem occurs I'll open new issue(s). 

Opened #21 because of notification for own message from other device.

The status changed in background notifications gone away and it seems to work as should 👍
