### ISSUE TITLE
File sizes wrong for outband images

### ISSUE THREAD

**Issue by tandr3w** [tinode/webapp#129]
**Describe the bug**
This might be a problem with the SDK instead of the webapp, not sure. When uploading a big image outband, when that image is previewed, it displays an incorrect file size.

**To Reproduce**
1. Get an image bigger than the max inband file size.
2. Upload the image.
3. Click the image to preview it.
4. The image size in the bottom-right corner is significantly smaller than the actual download size, it's not even close.

**Expected behavior**
The displayed size should be equal to the actual download size, or at least similar.

**Screenshots**
![Screenshot from 2023-08-11 15-27-36](https://github.com/tinode/webapp/assets/84942946/c359537b-9ed1-477f-a4e0-43ee1d547c55)
After downloading:
![image](https://github.com/tinode/webapp/assets/84942946/8b38fcd0-b77e-46cb-bcf1-eb8845ffe405)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Browser [e.g. Chrome, Safari]: Firefox
 - TinodeWeb Version: 0.22.8 (this happens on sandbox.tinode.co)

**Console log**
The correct size is showing when the message data is logged in the console, which makes me think that this is a client-side issue:
![image](https://github.com/tinode/webapp/assets/84942946/27bdbd88-8fe1-4e78-b3da-6f21d137000d)

**Additional context**
This seems to only happen to outband images. Inband images, videos, and other attachments are all working from what I've seen.

**Comment by or-else** [comment]
When you upload an image with dimensions larger than 1024 pixels, the image is scaled down to be under 1024, even for out-of-band images. So, the dimensions of the actually sent image could really be 1024x768.

**Comment by tandr3w** [comment]
> When you upload an image with dimensions larger than 1024 pixels, the image is scaled down to be under 1024, even for out-of-band images. So, the dimensions of the actually sent image could really be 1024x768.

I'm not talking about the size of the image, I'm talking about the file size, in bytes. The image I uploaded is clearly not 3.64 KB like it displays. When I download it from the chat, it's actually 318 KB.

**Comment by or-else** [comment]
Should be fixed now.
