### ISSUE TITLE
Add to homescreen with android isn't starting full screen / app mode

### ISSUE THREAD

**Issue by pwFoo** [tinode/webapp#13]
I tried to start the web app in app / full screen mode by adding it to homescreen with my android phone, but it still starts as browser tab.

Deployed tinode / web app with your docker mysql image. 
Maybe a problem with manifest file?

**Comment by or-else** [comment]
I guess it's because the app does not define any [service workers](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker).

**Comment by pwFoo** [comment]
Sure add to homescreen / app view needs service-worker?

App view works with your demo https://api.tinode.co, but with another problem.
```
{"ctrl":{"code":404,"text":"Not Found","ts":"2018-08-20T19:07:58.243Z"}}
```
Maybe wrong start url in manifest (with your demo)?
```
  "start_url": "/x/example-react-js/",
```

**Comment by pwFoo** [comment]
Maybe something wrong with the docker image (running ob my own domain) because searching Users by email, tel or username doesn't work. Only UserId works...
All fine with your demo.

**Comment by or-else** [comment]
> Maybe wrong start url in manifest (with your demo)?

Good catch, thanks! Fixed in dev. Keep in mind that you are the first one to try this. I have not tested adding to home screen.

**Comment by or-else** [comment]
> Maybe something wrong with the docker image (running ob my own domain) because searching Users by email, tel or username doesn't work. Only UserId works...

Please file a separate issue https://github.com/tinode/chat/issues/new
Don't forget to include the logs.

**Comment by or-else** [comment]
> because searching Users by email, tel or username doesn't work

I found and fixed a bug in the client-side code which may have affected searching for contacts. The update is pushed to devel https://github.com/tinode/webapp/commit/4aadff8ab356c3d090c9ab256ce3e0b4ab1232db. See if it works now. I'll close this issue. If the problem persists, please open a new one.

**Comment by pwFoo** [comment]
Problem still exists. Haven't debugged it deeper. Deployed tinode-mysql:0.15.5-rc5, added to homescreen and it still opens as browser tab.

I try to debug and fix it if I find some time at the weekend...

**Comment by or-else** [comment]
Thanks! I'll keep the issue open for further discussion.

**Comment by or-else** [comment]
Great, thanks! The next Docker build will include it.

**Comment by pwFoo** [comment]
Thanks, I'll update once it's published. 👍

**Comment by or-else** [comment]
Docker v0.15.5-rc6 published.

**Comment by pwFoo** [comment]
Fixed with rc6! 👍
