### ISSUE TITLE
No displaying the forwarded file

### ISSUE THREAD

**Issue by Mj-binary** [tinode/webapp#131]
**Describe the bug**
When you upload a file and then forward it to someone else, the file is not shown

**To Reproduce**
1. Alice sends a file to Bob
2. Alice forwards that message (including the file) to Carol
3. file not shown and carol only gets an empty bubble

**Expected behavior**
File and save button for carol will be displayed

**Screenshots**
![image](https://github.com/tinode/webapp/assets/67688484/a43c7ef2-c7eb-470d-9d91-25854e8852e7)

**Environment (please complete the following information):**
https://sandbox.tinode.co/

**Comment by or-else** [comment]
Thanks, fixed.

**Comment by Mj-binary** [comment]
Lots of Thanks.
