### ISSUE TITLE
Add members to groups fails

### ISSUE THREAD

**Issue by pwFoo** [tinode/webapp#17]
Searching user by name / email / UserId fails if I try to add a user to a group. 

No log entry during searching for User. No contacts found.

**Comment by or-else** [comment]
It's rather a feature than a bug. 

When starting a new topic, by default one sees a list of contacts. That list is supposed to be created by importing contacts from the mobile phone: the imported contacts are stored in the `fnd.private` field and the search for contacts is executed automatically on the _server_. In the same screen one can search for additional contacts by setting `fnd.public` field. The results of those searches are transient - they are not added to the list of permanent contacts and the value of `fnd.public` is not saved.

In the Group Management screen one is searching on the _client_ through the contacts returned by the most recent `fnd` query. In other words, one can only invite people who he already knows.  This is the logic followed by WhatsApp. Telegram does the same plus searches server-side for partial matches of user handles.

**Comment by pwFoo** [comment]
At the moment I have 3 users which are able to chat to each other. But no contacts available to be added to a group. 
So users I already chat with should be available as (known) contacts I think. 
With web client there are no contacts to read from client contacts. So default behavior should include active chat members / server side?

**Comment by or-else** [comment]
Yes, that's reasonable. I'll look into it.

**Comment by or-else** [comment]
Released in https://github.com/tinode/chat/releases/tag/v0.15.6-rc5

**Comment by pwFoo** [comment]
Add members from app contacts work fine in latest build 👍
