### ISSUE TITLE
Enter confirmation code without effect // hardcoded domain name in email

### ISSUE THREAD

**Issue by pwFoo** [tinode/webapp#19]
Hi I tried to verify by confirmation code after get the email.
Entered code and clicked confirm, but no effect.

Looked at the confirmation link but it's hardcoded to api.tinode.co. Activation was successful by modifiy the "Click" link to my own domain and then click confirm button works for me.

I just found one difference. Without link the code isn't in the url. If I use the (modified) link the code is included
```
https://<MODIFIED_DOMAIN>/#cred?method=email&code=808410
```

So it looks like the confirmation submit need to be fixed and the  verification email shouldn't be hardcoded to api.tinode.co.

**Comment by or-else** [comment]
Do you mean it's hardcoded in the docker container? I suppose it's not too hard to move it to a variable.

It's in the template and it's just a text file. You can edit it if you want.

**Comment by pwFoo** [comment]
Yes, I tested it with your docker image.
Fix it should be easy, but it needs to be configurable I think

**Comment by or-else** [comment]
Sure. I'll add a config option. Thanks.

**Comment by or-else** [comment]
Released in https://github.com/tinode/chat/releases/tag/v0.15.6-rc5

**Comment by pwFoo** [comment]
Is it TLS_DOMAIN? If I set it, it's no more available with my reverse proxy (ssl offloading). Is there a backend TLS dependency?

At the moment I need to modify the URL in the browser and append "&code=<CODE>" before submit the form with Confirm button. Without code in URL and form field code filled it doesn't work for me. I'll do some more testing...

**Comment by or-else** [comment]
It's `SMTP_HOST_URL`: https://github.com/tinode/chat/tree/devel/docker

**Comment by pwFoo** [comment]
Thanks, link is ok now!

But still I have to modify the URL.

Enter code manually fails (no visible submit action, just no reaction). Click the link bring me to the confirmation form, but I still need to set the code to the url

The way it works fine:

1. register a account
1. get the code by email
1. append "[...]&code=<CODE>" to the url
1. enter the code to the form field
1. submit / confirm button

Looks like the confirmation uses the URL GET param instead of the POST form field?

If you need more information I'll reproduce it and send you debugging information.

**Comment by or-else** [comment]
I don't understand the need for step 3. The code is added to the URL in the email as a fragment, i.e. `https://api.tinode.co/#code=123456`

> Looks like the confirmation uses the URL GET param instead of the POST form field?

I don't understand the question. The form in the webapp collects the code then sends it to the server over the websocket connection.

> If you need more information I'll reproduce it and send you debugging information.

Yes, please do. Thanks!

**Comment by pwFoo** [comment]
I create a account. Then I see the confirmation page.

![image](https://user-images.githubusercontent.com/333408/45929766-87b9e600-bf56-11e8-8fd8-3a1369dfdaa3.png)

But without `&code=<CODE>` in the url.
Now I enter the confirmation code get by email.

I click CONFIRM and nothing happens. No ajax call, no reaction.

![image](https://user-images.githubusercontent.com/333408/45929793-dd8e8e00-bf56-11e8-96e3-aefe9eea278c.png)

So I try the emailed link.
I have to login first and then I get an empty confirmation page without `&code=<CODE>` in the url and no prefilled CODE in the form!

![image](https://user-images.githubusercontent.com/333408/45929806-162e6780-bf57-11e8-9b05-f27965f17741.png)

I enter the code, and press CONFIRM button.
Again no action / request!

![image](https://user-images.githubusercontent.com/333408/45929815-3e1dcb00-bf57-11e8-956b-b10b8ff4ba01.png)

Now I refresh the page, modify the URL form `/#cred?method=email` to `/#cred?method=email&code=<CODE>`, fill in the code form field and press CONFIRM again with a successful action / request.

It's needed to
1. refresh the page
1. add the code to URL!
1. fill code form field
1. submit
to see a request to the backend and be able to get successful confirmed.

**Comment by pwFoo** [comment]
Because I need to authenticate user before I see the confirmation page the code isn't in the URL!
And without code in URL confirmation fails for me each time.

**Comment by or-else** [comment]
OK, I found it. It's due to this issue: https://github.com/facebook/react/issues/13015

I'll fix it ASAP.

**Comment by pwFoo** [comment]
Thanks for your great work!!! 👍 

With the second registered user the confirmation email is missing? Checked inbox and spam. Nothing. 
Any idea why first code is sent and second is missing?

**Comment by or-else** [comment]
I just checked. I receive messages for every new registrations.

**Comment by pwFoo** [comment]
Strange. 
First mail arrived to a small provider.
Two mails to gmail and one to another freemail provider not arrived.
Next confirmation mail to the first provider again works fine.
Is it provider dependent? With or without tls?

**Comment by or-else** [comment]
* If you are using gmail to send messages, check the Sent folder. GMail archives all outgoing messages there regardless of how they were sent.
* Check for bounced mail at the From: mailbox. You should see bounces for undelivered messages.
* Check the server logs:
```
docker exec -it name-of-the-running-container /bin/bash
cat /vat/log/tinode.log
```
Look for SMTP-related errors.

**Comment by or-else** [comment]
The error to look for in the logs is `Error sending validation email to`.

**Comment by pwFoo** [comment]
Outgoing I send it to a local email provider. 

The email is sent, but seems not rfc compliant?
```
550-5.7.1 not RFC 5322 compliant:
550-5.7.1 'From' header is missing.
```

It works fine provider internal if I send it with auth, but if the mail is send to an external provider (gmail, ...) it fails because of missing "From" header?

**Comment by or-else** [comment]
What's the format of your `SMTP_SENDER` env variable?

**Comment by or-else** [comment]
Interesting. The outgoing email does not have a `From` header indeed, but Gmail apparently adds it. Other providers may not.

**Comment by pwFoo** [comment]
SMTP_SENDER is set to the valid email address. 
```
-e SMTP_SENDER=<EMAIL_ADDRESS>
```

**Comment by pwFoo** [comment]
Thanks, I'll test it with the next docker image release.

**Comment by or-else** [comment]
0.15.7-rc1 is released with the change.

**Comment by or-else** [comment]
It's been fixed for a while. I assume everything is fine.
