### ISSUE TITLE
Mobile notification for own message sent from desktop :)

### ISSUE THREAD

**Issue by pwFoo** [tinode/webapp#21]
Hi @or-else 
I think notifications need filtered because mobile shows me an notification for my own message sent from desktop web client? *g*

**Comment by or-else** [comment]
Actually, maybe it's not a bug. Tell me, you are sending a message from a desktop client and getting a notification in a different client, like Android?

**Comment by pwFoo** [comment]
Chat from desktop web client with a contact and receiving (offline / closed browser) push notifications with my chrome for android web client for own messages. So if a meesage is sent by me, I shouldn't get a push notification about I think.
Not really a bug, more a config / setting thing *g*

**Comment by or-else** [comment]
Yes, I think it's reasonable. Thanks. 
It's easy to fix

**Comment by or-else** [comment]
It's been fixed since 0.15.7 release. Closing.
