### ISSUE TITLE
Runtime webapp update / reload?

### ISSUE THREAD

**Issue by pwFoo** [tinode/webapp#22]
After I deploy new tinode version I have problems with the webapp added to homescreen (for example enable / disable notifications doen't work, force reload page).

Maybe it should be possible to
1. reload (full screen) app with "swipe to reload"
1. webapp runtime update (download newer cached files like css, js or reinstall latest service worker) notification?

**Comment by or-else** [comment]
Do you have suggestions how to do it?

**Comment by pwFoo** [comment]
Both points I haven't worked with before, but I know there could be problems and I used web apps with a "client update available" notification html popup with reload / update button.

It's needed to force a service worker update it it is changed, because the installed service worker will be used until a newer version is installed.

Maybe it's needed to check client / server versions and trigger a update notification / script...

I think it isn't high prio at the moment, but should be considered.

**Comment by or-else** [comment]
Maybe you know some open source example which implement this feature?

**Comment by pwFoo** [comment]
The service worker will be updated by browser max-age limit (for example 1 day), but i read it's needed to trigger update()
https://stackoverflow.com/questions/41903097/how-to-force-service-worker-to-update

Example with cached app and update
https://medium.com/progressive-web-apps/pwa-create-a-new-update-available-notification-using-service-workers-18be9168d717

**Comment by or-else** [comment]
Thanks! I'll look into it next.
I'm currently setting up the infrastructure for translating the app into different languages.

**Comment by or-else** [comment]
Done: https://github.com/tinode/webapp/commit/00e48b7c93c15ef1db85ee0fc0aa906262c20e7f
