### ISSUE TITLE
Transmission confirmation with offline notifications

### ISSUE THREAD

**Issue by pwFoo** [tinode/webapp#26]
Tinode show different message states like WhatsApp.

1.  sent
1. delivered
1. read by recipient

I tested webapp with closed browser push notifications and looked at the message state.

The message is shown as still **not** delivered, but the android phone shows the received push notification. Sender still see "sent". Recipient opens the webapp and see one new / unread message in the chat / conversation list. 

Webapp is open, and the message is delivered, but still "sent" state.

Recipient opened the conversation with the new message and now the sender get the "delivered" and "read by recipient" indicator.

Would it possible to show the sent message as delivered (unread) after the recipient get the push notification about the new message?

**Comment by or-else** [comment]
> The message is shown as still not delivered, but the android phone shows the received push notification. 

This has nothing to do with push notifications. Push notifications are completely indepenent of delivery statuses. You probably have a network issue. 

> Webapp is open, and the message is delivered, but still "sent" state.

What do you see in the console? Please show client-side and server-side logs.

**Comment by or-else** [comment]
Please show client-side and server-side logs.

**Comment by or-else** [comment]
In the browser javascript console is usually located in Settings. Called Developer Tools or similar.

In the server see FAQ: https://github.com/tinode/chat/blob/master/docs/faq.md

**Comment by pwFoo** [comment]
I have to take a look how remote debugging is working...
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/?utm_source=dcc&utm_medium=redirect&utm_campaign=2016q3

**Comment by or-else** [comment]
There was no update on this issue for a while. Is it still relevant?
