### ISSUE TITLE
always sort chatList when invalidate

### ISSUE THREAD

**Issue by pcgpcgpcg** [tinode/webapp#35]
When invalidate,the chatList in contacts-view.js line 30:
 nextProps.chatList.map((c) => {
always sort whether chatLists have changed or not.

I think here should check if chatList changed like:
 const {chatList}=nextProps;
 if(chatList!==prevState.chatList){
      nextProps.chatList.map((c) => {

and at the final of getDerivedStateFromProps,
set new chatList to states like:
 return {
        chatList:chatList,
        contactList: contacts,
        archivedCount: archivedCount
      };

**Comment by or-else** [comment]
Yes, you are right that the sorting happens too often and it's bad. But I think the solution you are proposing is not the best one. The `getDerivedStateFromProps` should not be called at all. It should be refactored to use `componentDidUpdate` instead.

**Comment by pcgpcgpcg** [comment]
Great, hope your update

**Comment by or-else** [comment]
Fix released in https://github.com/tinode/webapp/releases/tag/v0.16.0
