### ISSUE TITLE
Web application does not work locally

### ISSUE THREAD

**Issue by wmwart** [tinode/webapp#36]
I cloned the application from the repository.
Next `yarn install`
Next problem https://github.com/tinode/webapp/issues/31(https://github.com/tinode/webapp/issues/31)
made the necessary changes
Next `npm run build:dev`
```
C:\_Projects\Tinode\webapp>npm run build:dev

> tinode-webapp@0.16.0 build:dev C:\_Projects\Tinode\webapp
> webpack --mode development --output ./umd/index.dev.js

Hash: a48930031c495acd1cf8
Version: webpack 4.39.3
Time: 2982ms
Built at: 2019-08-29 15:08:29
           Asset     Size  Chunks                    Chunk Names
    index.dev.js  568 KiB    main  [emitted]  [big]  main
index.dev.js.map  559 KiB    main  [emitted]         main
Entrypoint main [big] = index.dev.js index.dev.js.map
[0] multi ./src/index.js 28 bytes {main} [built]
[./src/config.js] 828 bytes {main} [built]
[./src/index.js] 941 bytes {main} [built]
[./src/lib/blob-helpers.js] 5.73 KiB {main} [built]
[./src/lib/host-name.js] 1.1 KiB {main} [built]
[./src/lib/local-storage.js] 1.48 KiB {main} [built]
[./src/lib/navigation.js] 2.83 KiB {main} [built]
[./src/lib/strformat.js] 1.56 KiB {main} [built]
[./src/lib/utils.js] 1.62 KiB {main} [built]
[./src/messages.json] 19.5 KiB {main} [built]
[./src/views/info-view.jsx] 26 KiB {main} [built]
[./src/views/tinode-web.jsx] 54.6 KiB {main} [built]
[react] external "React" 42 bytes {main} [built]
[react-dom] external "ReactDOM" 42 bytes {main} [built]
[react-intl] external "ReactIntl" 42 bytes {main} [built]
    + 52 hidden modules
```

End Run Error:
```
C:\_Projects\Tinode\webapp>node src\index.js
C:\_Projects\Tinode\webapp\src\index.js:3
import React from 'react';
       ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)

C:\_Projects\Tinode\webapp>
```
Please help launch. (

React v16.9.0
NodeJS v10.15.0

**Comment by or-else** [comment]
> Next problem #31

I've changed it to `/\.(js|jsx)$/` long time ago. What was exactly the problem and how did you solve it?

> import React from 'react';
>       ^^^^^
>
> SyntaxError: Unexpected identifier

Apparently `React` is not installed. did you run `npm install`?

Please do keep in mind that webapp is just the frontend. It won't work without the backend https://github.com/tinode/chat

**Comment by or-else** [comment]
Maybe it's something related to path separator `/` vs `\`? I'm on a Mac, you are probably on Windows.

**Comment by or-else** [comment]
I changed webpath config to use `path` package. It should fix windows vs mac/linux path problems.

**Comment by wmwart** [comment]
@or-else, thanks for the quick response! I am pleasantly surprised) 

> I changed webpack config to use path package. It should fix windows vs mac/linux path problems.

For build:dev it helped

> Apparently React is not installed. Did you run npm install?

Of course, React and all other dependencies settled normally.

> Please do keep in mind that webapp is just the frontend. It won't work without the backend https://github.com/tinode/chat

Tinode server is up and running

> Maybe it's something related to path separator / vs \? I'm on a Mac, you are probably on Windows.

Yes, I work on Windows

But...
```
C:\_Projects\Tinode\webapp>node src\index.js
C:\_Projects\Tinode\webapp\src\index.js:4
import React from 'react';
       ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)

C:\_Projects\Tinode\webapp>
```

For start `C:\_Projects\Tinode\webapp>node src\index.js` ?
It seems to me that the problem is not in `React`, but in `import`,
because if I delete the problem line, it will swear at the next one. What else can be fixed? (

**Comment by or-else** [comment]
Please attach your package-lock.json

**Comment by or-else** [comment]
OK, I understand now! You can't run it like `node index.js`. That's not a node module. It's a webapp.

Open it in your browser. Open something like http://localhost:6060/

**Comment by wmwart** [comment]
Wow! That works! )
Thank you very much.
Maybe I missed something, but is there a React component for embedding in my application?

**Comment by or-else** [comment]
It's downloaded by the browser:
https://github.com/tinode/webapp/blob/master/index.html#L19

**Comment by wmwart** [comment]
No, you did not understand me. I mean something like:
```
import Chat from 'React-Tinode';
...
<div>
    <Chat host='http://localhost:6060' options={{...tinodeOptions}}>
</div>
...
```
?

**Comment by or-else** [comment]
Ah, ok. Thanks for clarifying.

`<TinodeWeb />` is the component but it's not published separately from the rest of the app.

See here:
https://github.com/tinode/webapp/blob/master/src/index.js#L29
```
ReactDOM.render(
  <IntlProvider locale={language} messages={messages} textComponent={React.Fragment}>
    <TinodeWeb />
  </IntlProvider>,
  document.getElementById('mountPoint')
);
```

And the `mountPoint` is defined here:
https://github.com/tinode/webapp/blob/master/index.html#L31

**Comment by wmwart** [comment]
Thanks for the detailed answer.
Here you need to close issue?

**Comment by or-else** [comment]
Yes, please close the issue if you have received the answers. Thanks.
