### ISSUE TITLE
How to create a new group topic?

### ISSUE THREAD

**Issue by wmwart** [tinode/webapp#38]
I apologize for such questions. In the documentation for the client, I did not find a method for creating a group topic with parameters.

I began to parse webapp and found these functions:
```
  // Request to start a new topic. New P2P topic requires peer's name.
  handleNewTopicRequest(peerName, pub, priv, tags) {
    const topicName = peerName || this.tinode.newGroupTopicName();
    const params = {
      _topicName: topicName,
    };
    if (peerName) {
      // Because we are initialing the subscription, set 'want' to all permissions.
      params.sub = {mode: DEFAULT_ACCESS_MODE};
      // Give the other user all permissions too.
      params.desc = {defacs: {auth: DEFAULT_ACCESS_MODE}};
    } else {
      params.desc = {public: pub, private: {comment: priv}};
      params.tags = tags;
    }
    this.setState({newTopicParams: params}, () => {this.handleTopicSelected(topicName)});
  }

  // New topic was creted, here is the new topic name.
  handleNewTopicCreated(oldName, newName) {
    if (this.state.topicSelected == oldName && oldName != newName) {
      // If the current URl contains the old topic name, replace it with new.
      // Update the name of the selected topic first so the navigator doen't clear
      // the state.
      this.setState({topicSelected: newName}, () => {
        HashNavigation.navigateTo(HashNavigation.setUrlTopic('', newName));
      });
    }
  }
```

Where is the Tinode method call to create a group topic with parameters?

**Comment by or-else** [comment]
Here is the SDK method for creating a topic:
https://tinode.github.io/js-api/Tinode.Topic.html#subscribe

And here is the SDK documentation:
https://github.com/tinode/chat/blob/master/docs/API.md#sub

**Comment by wmwart** [comment]
Yes, but I don’t need a subscription.
What if topics are created by my server by calling the Tinode method?
The idea is that the server should create a topic, responding to certain non-user events, and add users to the topic who need to correspond with this event. They will see the topic when they enter the chat from the client.

**Comment by or-else** [comment]
Then you should look at `tn-cli`. It can be used to script the server:
https://github.com/tinode/chat/tree/master/tn-cli
