### ISSUE TITLE
Need help with Chinese translations

### ISSUE THREAD

**Issue by or-else** [tinode/webapp#40]
Need help translating strings to Chinese. Strings with messing translations are marked with `:!![MISSING]!!:`

https://github.com/tinode/webapp/blob/devel/src/i18n/zh.json

**Comment by usernameisnull** [comment]
still need?I see all have translated

**Comment by or-else** [comment]
Yes, I have google-translated the strings.

**Comment by or-else** [comment]
Thanks.
