### ISSUE TITLE
Web interface issues

### ISSUE THREAD

**Issue by danjde** [tinode/webapp#42]
Hi Devs!
We are an Italian associations (3x1t.org) and would like to add a Jabber/XMPP web interface to our web site.
Actually we use Converse.js but not so feel..
And we are searching an alternative.
So, we would like to know if TInode web support OMEMO and the auto chat room discover.
We have try the web interface https://web.tinode.co/# with our server parameters but the connection fails and we don't know why.

If Tinode Web suitable we could contribute to translate on Italian language and install it on our server ;-)

Thanks!

Davide

**Comment by or-else** [comment]
Tinode is not XMPP/Jabber. It's completely unrelated to XMPP other than servicing the same niche.

Re: OMEMO: Tinode does not support end-to-end encryption at this time.

Re: auto chat room discover: chat group will not appear in the UI unless (1) the user is invited to the chat by someone or something (i.e. an automated process) or (b) finds the chat through search and joins it.

**Comment by danjde** [comment]
> Tinode is not XMPP/Jabber. It's completely unrelated to XMPP other than servicing the same niche.

Ah! You are right!!
Excuse me excuse me excuse me! :-[

Ciao!
