### ISSUE TITLE
How to run tinode web chat using react?

### ISSUE THREAD

**Issue by prasetiko** [tinode/webapp#44]
Hi nice to meet you.

I'm new with tinode and react. I have downloaded tinode web chat react at https://github.com/tinode/webapp. When I make new react project and want to run it, I call npm start on cmd, but how about at tinode? I try using nmp run build:prod but nothing happen in my browser

**Comment by or-else** [comment]
See https://github.com/tinode/chat/blob/master/INSTALL.md

**Comment by prasetiko** [comment]
Thank you for your fast response, I am so glad.

I have installed before and save at tinode folder. Now, i have two files webbapp-master (react code) and tinode. When i try to run tinode folder it appear in browser, but I am still not understand how to run webapp-master.

**Comment by or-else** [comment]
You have to be more specific than that. Have you followed the installation instructions? Which path did you take?

**Comment by prasetiko** [comment]
Yes I have followed the installation instructions. Using installing from binaries

**Comment by or-else** [comment]
If you need help please be as specific as possible. Show logs, describe steps.

**Comment by or-else** [comment]
In general these kinds of discussions are more suited for the forum: https://groups.google.com/d/forum/tinode

**Comment by prasetiko** [comment]
This is the contents of my tinode folder
![image](https://user-images.githubusercontent.com/26808338/72881105-b3a7d000-3d32-11ea-8ef7-777ec7594331.png)
and when i follow the instruction on https://github.com/tinode/chat/blob/master/INSTALL.md and tinode will opened at browser
![image](https://user-images.githubusercontent.com/26808338/72881240-f8336b80-3d32-11ea-8fac-8a5c9ca39150.png)
This is the contents of my webapp-master folder who i get from https://github.com/tinode/webapp
![image](https://user-images.githubusercontent.com/26808338/72881389-434d7e80-3d33-11ea-988a-1210b7b38fb9.png)

What i want to know is, how do i get the result like the browser using webapp-master folder?

**Comment by or-else** [comment]
> What i want to know is, how do i get the result like the browser using webapp-master folder?

I do not understand what you mean "how do i get the result like the browser using webapp-master folder".

If the question is about configuring the location of a static folder, update config or add a command line parameter to the server and restart it.

**Comment by prasetiko** [comment]
Sorry, I think I miss calling webapp component in my react project. Do you have example for calling it?

**Comment by or-else** [comment]
https://github.com/tinode/webapp/blob/master/src/index.js#L31

**Comment by prasetiko** [comment]
I copy and paste to index.js. when i try to npm run build, it make eror like this
![image](https://user-images.githubusercontent.com/26808338/72961637-58361a80-3de4-11ea-999d-74f65780d90c.png)
Did i make a mistake?

**Comment by or-else** [comment]
Obviously you did not run `npm run build`. Your questions have nothing to do with Tinode. You need to learn or get help with general javascript programming.

**Comment by prasetiko** [comment]
> Obviously you did not run `npm run build`. Your questions have nothing to do with Tinode. You need to learn or get help with general javascript programming.

Nah i think my question is not clear enough





> > https://github.com/tinode/webapp/blob/master/src/index.js#L31
> > Sory I am not understand what i must to do with index.js
> 
> I have installed webapp to my project with npm i tinode-webapp, and now I need call component to my App.js. Could you please tell how to call it step by step?

this is what i mean

**Comment by or-else** [comment]
Please do not change your comments so much that they state different things.

Please move this conversation to https://groups.google.com/d/forum/tinode

**Comment by prasetiko** [comment]
Ah sory when I edit it, there is no comment from you. Maybe my connection
has a problem.

Oke I will move to that forum. Thanks

**Comment by xzmeng** [comment]
I had the same question until I noticed the `index.html` lying in the root directory.

This is not convenient during development. Every time I make a small change, it takes me a few seconds to run `npm run build: dev` and then reload it in Chrome to view the consequence.

I have little exposure to front-end so it would be much more helpful if there is a default live loading script like what the `npm start` does in the official react tutorial.
