### ISSUE TITLE
Convertsation jumps to the first message after showing an image

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/webapp#50]
When I click on some image, conversation jumps to the first message after I close the opened image.
See the screenshot - image with roses is the last received message. When I open and close it, I see the first message of the conversation - chat has jumped to the top.

![tinode6](https://user-images.githubusercontent.com/54183931/82425401-5e7c9080-9a7e-11ea-99e4-3979805393b3.png)

**Comment by or-else** [comment]
It's been fixed a while ago:
https://github.com/tinode/webapp/commit/c9d05642e2c7cb039b044d6a134c6c0e5a679833

**Comment by sanmiguel2019** [comment]
Ok, if it's fixed I close the issue. I opened it because on Sanbox I still see the same problem. Probably it's just not updated.
