### ISSUE TITLE
Received by recipient also if push notification is triggered?

### ISSUE THREAD

**Issue by pwFoo** [tinode/webapp#51]
At the moment a message is marked as sent, but not received also if the recipient have received a push notification.

Message should marked as delivered (but unread) also if tinode is closed, but the recipient device have received a push notification?

**Comment by or-else** [comment]
> At the moment a message is marked as sent, but not received also if the recipient have received a push notification.

Android? iOS? Web?

> Message should marked as delivered (but unread) also if tinode is closed, but the recipient device have received a push notification?

Yes, it should be marked as delivered.

**Comment by pwFoo** [comment]
Sorry, removed that part during I write my text...

Web client, Chrome Browser

**Comment by or-else** [comment]
Fetch on push is not implemented in the webapp.

**Comment by or-else** [comment]
I think this is done now.
