### ISSUE TITLE
The downloaded file is damaged

### ISSUE THREAD

**Issue by wYuJian** [tinode/webapp#57]
console.log(Drafty.getDownloadUrl(data));
            console.log(Drafty.getEntityMimeType(data));
            console.log(Drafty.getEntitySize(data));
            console.log(Drafty.getContentType(data));
            let url = Drafty.getDownloadUrl(data);
            let filename = data.name;
            let mimetype = Drafty.getEntityMimeType(data);
            const nim = this.$store.state.nim;//Vuex  new() Tinode
            var downloader = nim.getLargeFileHelper();
            downloader.download(url, filename, mimetype);
            downloader
                .download(url, filename, mimetype, loaded => {
                    console.log(loaded);
                })
                .then(() => {
                    // this.setState({ downloader: null, progress: 0 });
                })
                .catch(err => {
                    console.log(err.message);
                });

**Comment by or-else** [comment]
If you are reporting a bug, please fill out the bug report form. If you are asking a question, please write to https://groups.google.com/forum/#!forum/tinode
If you have difficultly writing in English, write an explanation in your language and I will try to understand it using translate.google.com
