### ISSUE TITLE
It´s not possible to change MAX_INBAND_ATTACHMENT_SIZE value

### ISSUE THREAD

**Issue by thinkingheads** [tinode/webapp#58]
It´s not possible to change the default

`export const MAX_INBAND_ATTACHMENT_SIZE = 195584;`

value . I am trying to decrease it to avoid saving images and files in MySQL. When I put any other value smaller or greater, appears this error:

`blob-helpers.js:114 Uncaught ReferenceError: bytesToHumanSize is not defined at Image.N.o.onload (blob-helpers.js:114)`

**Comment by or-else** [comment]
This feature was been released in 0.16.9-rc1
