### ISSUE TITLE
Not found https://cdn.jsdelivr.net/npm/react-intl@5.10.14/dist/react-intl.min.js

### ISSUE THREAD

**Issue by mzch** [tinode/webapp#63]
If you ant to ask a question, please post to https://groups.google.com/d/forum/tinode instead.
---

**Describe the bug**
Not found `https://cdn.jsdelivr.net/npm/react-intl@5.10.14/dist/react-intl.min.js`

**Expected behavior**
Show tinode screen normally.

**Screenshot**
<img width="1501" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/107727613-033aae80-6d2f-11eb-8a66-0c4c8a669284.png">

**Comment by or-else** [comment]
Version?

**Comment by mzch** [comment]
V0.16.10, commit 924459f84bd10944043877a1f1e8b5315411042b

**Comment by mzch** [comment]
I can't find `react-intl@5.10.14/dist/react-intl.min.js` in `https://www.jsdelivr.com/package/npm/react-intl`.
Is it `https://cdn.jsdelivr.net/npm/react-intl@5.10.14/react-intl.umd.min.js`?

**Comment by or-else** [comment]
Just change it on your end to correct path. See paths at sandbox.tinode.co

**Comment by mzch** [comment]
Great! Thanks.
