### ISSUE TITLE
GRPC: group owner can not grant "delete" permission to a group member

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/webapp#65]
User `usrHGshCFWe5aI` is owner of the group `grpi4CSwukyuPQ`. Now group's owner want to grant "delete" permission to the group member **yoyoyo** ( `usrpDPgde-kKYI`)

I2021/03/09 08:58:20 grpc: session started Qxm2-_EMNA4 188.165.249.27:56434 2
I2021/03/09 08:58:20 grpc in: hi:<id:"644209" user_agent:"php/grpc" ver:"1" lang:"es-ES" >  Qxm2-_EMNA4
I2021/03/09 08:58:20 grpc in: login:<id:"198929" scheme:"token" secret:"\266\323\3202\336P\365\254\241\010K`\036\000\001\000\001\000Q\023\323<\230'\340\326k\326\316T6e\037x\312=|SJM\241\210\205\310\030!\017Z:\342" > auth_level:ROOT  Qxm2-_EMNA4
I2021/03/09 08:58:20 grpc in: sub:<id:"775653" topic:"grpi4CSwukyuPQ" get_query:<what:"desc" > > on_behalf_of:"usrHGshCFWe5aI" auth_level:ROOT  Qxm2-_EMNA4
I2021/03/09 08:58:20 grpc in: set:<id:"645043" topic:"grpi4CSwukyuPQ" query:<sub:<user_id:"usrpDPgde-kKYI" mode:"JRWPD" > > > on_behalf_of:"usrHGshCFWe5aI"  Qxm2-_EMNA4

The request is successful but permissions don't change and user  `usrpDPgde-kKYI` don't see the option to delete messages posted by other users (delete for all).

When I check permissions for user `usrpDPgde-kKYI` in the members' list I don't see the permission "D".

![group1](https://user-images.githubusercontent.com/54183931/110446892-901b2280-80b7-11eb-85b4-d73e023fe492.png)

However, when I click on "Edit permissions" for user **yoyoyo** ( `usrpDPgde-kKYI`) I see that permission "D" is checked:

![group2](https://user-images.githubusercontent.com/54183931/110447476-2f401a00-80b8-11eb-89d6-a5e40a86e534.png)

As I see the problem is only with permission "D". For example, if if group owner removes permission "W" for a user, it works and user can not write messages anymore.

It looks like a bug.

**Comment by or-else** [comment]
It's by design. The user has to accept it:

![110447476-2f401a00-80b8-11eb-89d6-a5e40a86e534](https://user-images.githubusercontent.com/5938143/110517238-a8248d80-811b-11eb-89c4-3170ba522e5e.png)

**Comment by sanmiguel2019** [comment]
Ok, thanks.
