### ISSUE TITLE
Webapp: reconnectiong problems in mobile phones

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/webapp#67]
I don't see these problem always but periodically.

**Problem 1**

I leave home where I use wifi and phone automatically connects to the mobile Internet. I turn on phone's screen with Tinode's webapp already open and I see message "Disconnected. Reconnecting in...". It's normal and nothing strange here. The problem starts when sometimes I see message like "reconnecting in" a few minutes. For example:

![reconnect](https://user-images.githubusercontent.com/54183931/111488116-dc5a0880-8730-11eb-9950-40fd9405d076.png)

I was not able to send a message almost 3 minutes. And the message even didn't show the link "Retry". I reloaded the webapp and it immediately connected.

**Problem 2**

The same scenario. I leave home where I use wifi and phone automatically connects to the mobile Internet. I turn on phone's screen and see message in the webapp "Disconnected. Reconnecting in 1..." and a link "reconnect". But his message does not disappear. Sometimes there is a link "Retry" but sometimes not. Even if there is a link and I tap on it, absolutely nothing happends.

![reconnect2](https://user-images.githubusercontent.com/54183931/111489741-50e17700-8732-11eb-9a02-367648b89b63.png)

The message just hangs and doe snot disappear despite to the fact that webapp already has established connection to the server. How do I know it? When this message "reconnecting in 1" I see in the contacts list, I can access any topic, send messages and I don't see "Disconnected" message anymore. For some reason it doe snot disapper after establishing connection.

**Possible solutions**

I don't know the solution for problem 2. For problem 1, I guess it should work in the following way. When phone's screen has been off and user turns it on, and the webapp is disconnected, it should retry reconnecting immediately.  And only then if connection could not be established, set a timeout.

It's the same like with online/offline status, Tinode should fix when phone's screen is off and when is on (or browser tab with webapp is not visible / visible in a case of computer) - reset reconnection time when Tinode's webapp becomes visible, set online/offline status when the app is visible/not visible.

**Comment by or-else** [comment]
Would you like to send a pull request?

**Comment by or-else** [comment]
I've added a possible fix in https://github.com/tinode/webapp/issues/67. Please tell me if it helps.

**Comment by or-else** [comment]
Have you had a chance to check if it's fixed? I'm going to release 0.17.0 next week.

**Comment by sanmiguel2019** [comment]
Sorry, I was away. Tomorrow I will check it.

**Comment by sanmiguel2019** [comment]
I tested it yesterday. Usually the problem appears when phone loses wifi connection and switches to mobile Internet or loses any Internet connection for some time. The problem seemed to be resolved but then when I returned home and my phone connected to the wifi, appeared this:

![app](https://user-images.githubusercontent.com/54183931/116375598-5937d200-a807-11eb-94bc-2e9d9831611c.png)


When I opened the app I saw a message like "Reconnecting in 3". When the counter reached "0", the message did not disappear, it continued with negative numbers like 0... -1... -2...-3

Actually, connection was already established but this message did not disappear. I tapped on a conversation, sent a message but when returned to the contacts list I still saw this message counting negative numbers.

**Comment by sanmiguel2019** [comment]
I did one more test. My phone didn´t lose the connection. I just turned the screen off leaving the webapp open. When I turned the screen on again I saw message saying that reconnection will be done in 30 and something seconds (too long time). I turned the screen off and on again without waiting without waiting to be reconnected. The counter didn´t reset - it continued counting down from the number I saw befire turning off the screen. I am not sure but I guess that the app doesn´t reset the counter correctly on screen on/off.

![app7](https://user-images.githubusercontent.com/54183931/116435397-34615000-a843-11eb-8a92-a466b5e0a1d2.png)

**Comment by or-else** [comment]
Added another fix: 273e34d
Please see if it helps.

**Comment by sanmiguel2019** [comment]
I tested it a few times and didn't see the problem anymore. I am going out now and periodically will open the webapp to check if the problem appears. In a few hours I will post again.

**Comment by sanmiguel2019** [comment]
Probably you can close this issue. I don't see reconnecting messages that hangs nor counter with negative numbers. The app reconnects in a few seconds. Only once saw message that the app will reconnect in some 15 seconds when my phone were iddle for a long time.

**Comment by sanmiguel2019** [comment]
Actually, I don't know. I was out for running. In some places of my route there is no mobile internet. I opened Tinodes web app many times but did not see the connection time increasing so much. I returned home, the phone connected to wifi. I turned on the screen, Tinode reconnected in a few seconds. I turned off the screen. When I turned on the screen again appeared this:

![tin8](https://user-images.githubusercontent.com/54183931/116759579-9324f600-aa0a-11eb-8bdf-e6ec3f7c9570.png)

Probably it's because

**Comment by or-else** [comment]
Please list steps to reproduce.

**Comment by sanmiguel2019** [comment]
It's not reproducible. I can not understand the pattern. 
This morning I was testing another things. I turned phone's screen off leaving Webapp open with some topic selected. After turning the screen on again I saw message "Reconnecting in 1..." that did not disappear. I tried to send a message but it was not possible - message "Reconnecting in 1..." disappeared but appeared another error:

![app26](https://user-images.githubusercontent.com/54183931/118791109-4eb0ab80-b88e-11eb-8c83-050da0d011ec.png)

After a few seconds appeared again the message "Reconnecting in 5..." After 5 seconds it disappeared and message was sent.

In the last time I often see message "Can not publish on inactive topic".

**Comment by or-else** [comment]
I have found a bug which may explain it. The fix will be live in the next version.

**Comment by or-else** [comment]
It should be fixed in 0.17.2-rc3
