### ISSUE TITLE
Message previews internationalization and style

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/webapp#69]
I don'[ t know how to submit pull requests to the devel, so I post it here.

Message previews feature in the contacts list is great but it needs to be internationalized. draftyFormatter should use different colors. If not, type of the message - "Image", "File" etc looks like the first word of a message.

**Below are my suggested changes:**

**/src/i18n/en.js**

Add lines:
```
"prev_image": "Image",
"prev_file": "File",
"prev_form": "Form"
```

**/src/i18n/es.js**

Add lines:
```
"prev_image": "Imagen", 
"prev_file": "Archivo",
 "prev_form": "Formulario"
```

**/src/i18n/ru.js**

Add lines:
```
"prev_image": "Изображение",
"prev_file": "Файл",
 "prev_form": "Форма"
```

The same should be done in Chinese, Korean etc. Unfortunately, I don't know these languages

**/src/widgets/contact.jsx**

change line;
`values = [<i key="im" className="material-icons">photo</i>, 'Picture'];`
to:
`values = [<i key="im" className="material-icons color_prev">photo</i>, <span className="color_prev"><FormattedMessage id="prev_image" defaultMessage="Image" description="Image" /></span>];`

change line:
`values = [<i key="fm" className="material-icons">dashboard</i>, 'Form: '].concat(values || []);`
to:
`values = [<i key="fm" className="material-icons color_prev">dashboard</i>, <span className="color_prev"><FormattedMessage id="prev_form" defaultMessage="Form:" description="Form" /></span>].concat(values || []);`

change line:
`values = [<i key="ex" className="material-icons">attachment</i>, 'Attachment'];`
to:
`values = [<i key="ex" className="material-icons color_prev">attachment</i>, <span className="color_prev"><FormattedMessage id="prev_file" defaultMessage="File" description="File" /></span>];`

**/css/base.css**

add line:

`.contact-comment .material-icons .color_prev,.color_prev{color: #A0CDF5;}`

(Probably it's not a perfect solution for css.)

**Result:**

![app4](https://user-images.githubusercontent.com/54183931/116417440-299ebf00-a833-11eb-9548-8e7865288add.png)

If a message contains not only image but also text, I guess, there is enough only to show image icon in the preview, without the word "Image". It only occupies space and icon already indicates that a message contains image. But i't not so important.

**Comment by or-else** [comment]
Thanks for pointing it out. Translations added in f6acbaa.

**Comment by or-else** [comment]
I think this is done.
