### ISSUE TITLE
Webapp tries to upload files to the server where the app is hosted instead of Tinode´s server.

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/webapp#71]
It´s not possible to upload large files if webapp is not hosted on the same server where Tinode is running.

Webapp is hosted on, for example: https://tinode-webapp.com
Tinode is running on, for example: https://tinode-server.com

When I try to upload large files, I get 404 error:

![app19](https://user-images.githubusercontent.com/54183931/116978645-e83b6300-acbb-11eb-9e2e-9ac939248db5.png)

As you can see, there is no hostname and that´s why Webapp tries to upload files to the same server instead of Tinode's server.

in my `/src/config.js` file I have the same hostname for hosted and local:
`export const KNOWN_HOSTS = {hosted: 'tinode-server.com', local: 'tinode-server.com'};`
as I don´t run Tinode locally.

Logically it would be that Webapp uploads files to KNOWN_HOSTS that use to connect to Tinode's server instead of host where Webapp is located but it's not the case.

The only way is to achieve the correct uploading is to modify `tinode.prod.js` file and replace
`let o="/v0/file/u/";`
with
`let o="https://tinode-server:6060/v0/file/u/";`

**Comment by or-else** [comment]
Please use forum to ask questions.

**Comment by sanmiguel2019** [comment]
I use forum to ask questions but this looks like a bug - webapp connects to one server but when sending files tries to connect to another server.

**Comment by or-else** [comment]
I believe this has been addressed. Please verify.
