### ISSUE TITLE
Push about new message, but not received in the webapp

### ISSUE THREAD

**Issue by pwFoo** [tinode/webapp#72]
**Describe the bug**
Since I updated to 0.17.0(rc/stable) messages not appear in chat. I updated because of some problems (js libs missing), ran in push notification problems and now solved with latest rc / stable release 0.17.0, but now messages missing in chats. I get a push notification about a new message, but isn't shown if I open the webapp and chat window.

**To Reproduce**
1. wait for a push notification
2. open webapp
3. searching for the new message

**Expected behavior**
See the new massage at contacts chat.

**Environment (please complete the following information):**
 - OS: Win 10 and Android
 - Browser Chrome
 - TinodeWeb Version 0.17.0

**Comment by or-else** [comment]
Things work as expected in my installation.

**Comment by pwFoo** [comment]
I use my tinode installation with a friend for testing and we have both the same problem. s
Started after I updated because of the changed url for libs breakting the webapp. Updated to 0.17.0 rc release to fix it. Persists with 0.17.0 stable too.

Difficult to collect more information because bug is during webapp is closed and I get push notification. Not every time I get a new message.

**Comment by or-else** [comment]
Please list steps to reproduce.

**Comment by pwFoo** [comment]
See initial post...

Wait with closed app until contact write a message. See push notification. Open webapp and the new message is missing. Not shown. Wait some time, close and open webapp some times. Or write an answer that message isn't received by the webapp. 

Don't know what "fixes" it, but some time later the message will be there if I open the webapp one or more times again...

**Comment by or-else** [comment]
> See initial post...

Works for me. If it does not work for you, please list steps to reproduce.

**Comment by or-else** [comment]
Keep in mind that for pushes to work the app has to be in the background and the user receiving the pushes should not be actively attached to topic with the conversation.

**Comment by pwFoo** [comment]
Hi or-else,
looks like tinode webapp go back to older / replaced version?
```
[07:09:21.290] out: {"hi":{"id":"120847","ver":"0.17.0-rc3","ua":"TinodeWeb/0.17.0-rc3 (Chrome/90.0; Win32); tinodejs/0.17.0-rc3","dev":"<163, bytes: e8JOc5HwPWKP...qw48QhKUafqE>","lang":"de-DE","platf":"web"}} 
```

Removed all app data / caches, logged in again.
Push notifications can't be activated first time. Reload in Browser, than it was possible to activate checkbox / push.

Maybe it's solved now?
```
[07:13:29.036] out: {"hi":{"id":"107204","ver":"0.17.0","ua":"TinodeWeb/0.17.0
```

webapp should reload / ask for reload with a button on version update?

**Comment by pwFoo** [comment]
Still the same. Messages Not appear in webapp. Need to close and open one or more times until messages are loaded. No console with my Android Phone

**Comment by or-else** [comment]
> looks like tinode webapp go back to older / replaced version?

Clear this cache:

![image](https://user-images.githubusercontent.com/5938143/117583184-65c50000-b10e-11eb-9246-92d6eb93cbcd.png)

> Push notifications can't be activated first time. 

What does it mean? You click the box and then what?

> Messages Not appear in webapp. 

How do I reproduce?

**Comment by pwFoo** [comment]
Cleared all caches before.
After clearing that cache again last (todoay) disappeared messages shown again.

Try to reproduce it again with desktop / mobile...

**Comment by pwFoo** [comment]
Still the same problem. No message appears after notificated. Need to close / open webapp over some minutes until message appears and tinode is usable again until next message arrives during webapp is closed.

So it works until the next message received with webapp closed...

**Comment by or-else** [comment]
List steps to reproduce.

**Comment by pwFoo** [comment]
I know you can't reproduce it with your setup and understand if that is not comprehend...
But it's frustration to me too...

Each time I get a message with closed browser (push notification) message isn't shown. If I answer in the topic the missing messages shown as deleted. 
I need to close an open the webapp some times until messages appear.

**Comment by pwFoo** [comment]
Looks like https://github.com/tinode/webapp/tree/v0.17.1-rc1 fixes that bug!
Tested with mobile, desktop and a friend remote and messages shown as should again...

**Comment by pwFoo** [comment]
Hi @or-else, I updated to v0.17.5 and problem with webapp is fixed... 
Just to let you know.
