### ISSUE TITLE
Fetch message on receiving push notification

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/webapp#74]
**Is your feature request related to a problem? Please describe.**

Yes, this feature request is related to a problem. If Webapp is connected to the server and user appears online, messages sent to this user should be marked as delivered. If not, "delivered" is an pointless option because show status "delivered" only if a particular topic is selected. This results in a completely incomprehensible functioning of the application.

**Example.**

User A sends message to user B who appears online but HAS NOT selected the topic of user A. Sent message does not appear as delivered.

User A sends message to user C who appears online but HAS selected the topic of user A. Sent message appears as delivered.

User A can not understand - why some messages sent to online users appear as delivered but some not. This situation is strange - user is online but does not receive messages.

**Describe the solution you'd like**

1. Webapp that is connected to the server should receive all messages immediately, not only for the selected topic.
2. If message arrives to a selected topic and browser tab with this topic is visible, message should be marked as received and read. If it's not visible (or user has selected another topic) it should be marked only as received.
3. Instant delivery of messages could fix the problem with updating previews of the messages in the contacts list.

**Describe alternatives you've considered**
If there is no instant delivering of messages to the device, if recipient is online, all the messages sent to this person should be marked as delivered in some other way.

**Comment by or-else** [comment]
It's not about *marking* them as delivered. It's about actually delivering them and then marking as delivered. This is done in iOS and Android apps. Would you like to add this feature to the web app as well?

**Comment by or-else** [comment]
This will be in the next release, together with video calls.

**Comment by or-else** [comment]
Released a while ago. Closing.
