### ISSUE TITLE
 Out of sort memory, consider increasing server sort buffer size

### ISSUE THREAD

**Issue by young310** [tinode/webapp#83]
**Describe the bug**
The web app cloud not load content with following console log:
W2021/07/30 04:46:27 topic[p2pufmTQEX6s54lRXk4HM_rwg] handleSubscription Get.Data failed: Error 1038: Out of sort memory, consider increasing server sort buffer size sid=WQlsuuQwB94

**To Reproduce**
1. Use android app send any message including short text message
2. Click on send
3. Log into web app

**Expected behavior**
If the web app go offline, using android app send any text message will not load in web app, even a short text.
But if the user is online using web app, everything work fine.
It is expected to show normally with the chat history.

**Screenshots**
<img width="481" alt="Screen Shot 2021-07-30 at 13 25 30" src="https://user-images.githubusercontent.com/8056293/127604870-cad0337c-15ca-48a2-b29d-a3551addc209.png">

**Environment (please complete the following information):**
 - OS: ubuntu / mac
 - Chrome
 - TinodeWeb Version 0.17.6

**Console log**
W2021/07/30 04:46:27 topic[p2pufmTQEX6s54lRXk4HM_rwg] handleSubscription Get.Data failed: Error 1038: Out of sort memory, consider increasing server sort buffer size sid=WQlsuuQwB94

**Additional context**
If the web app go offline, using android app send any text message will not load in web app, even a short text.
But if the user is online using web app, everything work fine.

**Comment by or-else** [comment]
You are sending large files in-band instead of out-of-band. You misconfigured either your server or clients or both.

**Comment by young310** [comment]
> You are sending large files in-band instead of out-of-band. You misconfigured either your server or clients or both.

I configure the server to use S3, and there is no error message.
How do I know if the file upload to S3 works? I didn't see any thing on S3 bucket.

**Comment by or-else** [comment]
I don't know what you did wrong exactly but your are sending your file attachments in-band, meaning you send them in a message as bytes instead of uploading then to s3 and sending a link.

**Comment by young310** [comment]
> I don't know what you did wrong exactly but your are sending your file attachments in-band, meaning you send them in a message as bytes instead of uploading then to s3 and sending a link.

I increase the "max_message_size" to 10X and is it possible that the server does not read the blob type but only decide by the size of blob?

**Comment by or-else** [comment]
Don't increase it to 10x.
