### ISSUE TITLE
password reset page not showing properly

### ISSUE THREAD

**Issue by young310** [tinode/webapp#90]
**Describe the bug**
When receiving the reset notification email, whether you click on the link or copy paste to the browser, 
the reset password page will not show for the first time.
you can copy paste the url to the previously opened tab to make it work.

**To Reproduce**
1. Go to the website, send forgotten password email
2. Click on the reset link
3. See error
4. Copy, paste the url in a new tab will also see error
5. only paste to the previously opened tab will work
![Screen Shot 2021-11-30 at 17 50 25](https://user-images.githubusercontent.com/8056293/144024785-19266293-b6ec-4369-9fe8-e259516027b0.png)

**Expected behavior**
show reset password page
![Screen Shot 2021-11-30 at 17 50 41](https://user-images.githubusercontent.com/8056293/144024758-12ddfc2b-def1-4c44-ab20-6e2c3ddf6962.png)

**Screenshots**

**Environment (please complete the following information):**
 - OS: Mac OS
 - Browser: both Chrome and Safari
 - TinodeWeb Version 0.17.10

**Console log**
NA

**Comment by or-else** [comment]
Confirmed

**Comment by or-else** [comment]
Fixed in 6a87762

**Comment by or-else** [comment]
released in -rc2
