### ISSUE TITLE
langauge is not defined

### ISSUE THREAD

**Issue by young310** [tinode/webapp#91]
If you want to ask a question, please post to https://groups.google.com/d/forum/tinode instead.
---

**Describe the bug**
I try to update webapp to 0.18.2 and got the error message on homepage.

**To Reproduce**
1. Go to homepage
2. will get empty page
3. open console
index.js:26 Uncaught ReferenceError: langauge is not defined
    at index.js:26:42
    at index.prod.js:1:268451

**Expected behavior**
load the login page

**Screenshots**

![Screen Shot 2022-03-07 at 16 37 24](https://user-images.githubusercontent.com/8056293/156996403-6bf12655-432c-4314-9ce6-0fec6b157e5c.png)

**Environment (please complete the following information):**
 - OS: Mac
 - Browser Chrome, Safari
 - TinodeWeb Version 0.17

**Console log**
index.js:26 Uncaught ReferenceError: langauge is not defined
    at index.js:26:42
    at index.prod.js:1:268451

**Additional context**
NA

**Comment by or-else** [comment]
I cannot reproduce with 0.18.2:

<img width="1203" alt="Screenshot 2022-03-07 at 08 53 32" src="https://user-images.githubusercontent.com/5938143/157080542-4968998e-365f-4fcb-a02f-372372ebb575.png">

The error "Failed to initialize push notifications" is expected: Safari is intentionally crippled by Apple.

**Comment by young310** [comment]
@or-else 
Same in dev version, there is no missing package from console and network tabs.

Uncaught ReferenceError: langauge is not defined.             index.dev.js:13504 
    at index.dev.js:13504:74
    at index.dev.js:13512:3
    at index.dev.js:13514:12
(anonymous) @ index.dev.js:13504
(anonymous) @ index.dev.js:13512
(anonymous) @ index.dev.js:13514
