### ISSUE TITLE
Can't open in chrome 

### ISSUE THREAD

**Issue by damoncoo** [tinode/webapp#95]
**Describe the bug**
Tindeo Web can not opened in chrome

**To Reproduce**
1. Run npm build and serve
2. Open in chrome 

**Expected behavior**
Opened in chrome properly

**Screenshots**

<img width="1230" alt="截屏2022-05-20 09 34 04" src="https://user-images.githubusercontent.com/4880373/169431596-a6692ab2-b166-4d36-a636-ff6d6428e3cb.png">
<img width="1042" alt="截屏2022-05-20 09 33 33" src="https://user-images.githubusercontent.com/4880373/169431600-3d24801b-a39f-46e9-bff4-23b5256ecda0.png">

**Environment (please complete the following information):**
 - OS:  MacOS 12.3.1
 - Browser  Chrome 
 - TinodeWeb Version 0.18.6

**Console log**
Uncaught ReferenceError: React is not defined
    at Object.react (external var "React":1:1)
    at __webpack_require__ (bootstrap:19:1)
    at make namespace object:7:1
    at index.dev.js:13511:3
    at index.dev.js:13513:12

**Additional context**
NO

**Comment by or-else** [comment]
> Run npm build and serve

Please read https://github.com/tinode/webapp#installing-and-running

**Comment by damoncoo** [comment]
> > Run npm build and serve
> 
> Please read https://github.com/tinode/webapp#installing-and-running

I have backend installed,  serve with this command
`tinode -static_data /Users/Darcy/Desktop/code/webapp -config tinode2.conf`

**Comment by or-else** [comment]
0.18.6 is running just fine at sandbox.tinode.co:

![Screenshot_20220519-215920](https://user-images.githubusercontent.com/5938143/169453805-e1f293de-2dd7-4199-9379-7526ae3f51c1.png)

**Comment by damoncoo** [comment]
Figured out why, jsdelivr resource not loaded in chrome. Weird, it is working now
