### ISSUE TITLE
USER_NEW is not defined

### ISSUE THREAD

**Issue by young310** [tinode/webapp#98]
**Describe the bug**
When I register the user, the system prompt USER_NEW is not defined

**To Reproduce**
1. Create new user
2. Input everything and click register
3. See error

**Expected behavior**
Create an user account

**Screenshots**
<img width="282" alt="Screen Shot 2022-05-31 at 17 16 35" src="https://user-images.githubusercontent.com/8056293/171139041-48df08a4-43df-4605-9713-f2ffa1ecc220.png">

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - TinodeWeb Version 0.20.0-beta1/tinodejs 0.19.0-rc1
 - TinodeServer Version 0.20.0-beta1

**Console log**
I2022/05/31 09:10:24 in: '{"hi":{"id":"83695","ver":"0.19.0-rc1","ua":"OnCallWeb/0.20.0-beta1 (Chrome/102.0; MacIntel); tinodejs/0.19.0-rc1","lang":"zh-TW","platf":"web"}}' sid='ZSRdWr-unBw' uid=''
I2022/05/31 09:11:11 ws: session started BdaqRi5CiZA 1.200.25.106:54490 1
I2022/05/31 09:10:24 in: '{"hi":{"id":"83695","ver":"0.19.0-rc1","ua":"OnCallWeb/0.20.0-beta1 (Chrome/102.0; MacIntel); tinodejs/0.19.0-rc1","lang":"zh-TW","platf":"web"}}' sid='ZSRdWr-unBw' uid=''
I2022/05/31 09:11:11 ws: session started BdaqRi5CiZA 1.200.25.106:54490 1

**Additional context**
Server log
I2022/05/31 09:10:24 in: '{"hi":{"id":"83695","ver":"0.19.0-rc1","ua":"OnCallWeb/0.20.0-beta1 (Chrome/102.0; MacIntel); tinodejs/0.19.0-rc1","lang":"zh-TW","platf":"web"}}' sid='ZSRdWr-unBw' uid=''
I2022/05/31 09:11:11 ws: session started BdaqRi5CiZA 1.200.25.106:54490 1

**Comment by or-else** [comment]
Thanks, fixed in https://github.com/tinode/tinode-js/commit/bc45065deef2319e4012f45075466563d45c0af7
